<?php
/*
 * This file was automatically generated By Code Smith 
 * Modifications will be overwritten when code smith is run
 *
 * PLEASE DO NOT MAKE MODIFICATIONS TO THIS FILE
 * Date Created 5/6/2012
 *
 */

/* <summary>
 * Implementations of sldistricts represent a 
 * </summary>
 */
class Model_Tracker
{		   
	#region PRESERVE ExtraMethods For 
	#endregion
	#region Contants	
	const ACT_ADD							= 10;
	const ACT_UPDATE						= 11;
	const ACT_DELETE						= 12;
	const ACT_CHANGE_PAGE					= 13;
	const ACT_SHOW_EDIT                     = 14;
	const ACT_GET                           = 15;
	const NUM_PER_PAGE                      = 15;
	
	const TBL_SL_TRACKER		            = 'sl_tracker';
	
	const SQL_INSERT_SL_TRACKER		= 'INSERT INTO `{0}`
		(
            `TrackID`,
            `UserID`,
            `TrackType`,
            `Value`,
            `Description`,
            `TrackDate`
		)
		VALUES (
		\'{1}\', \'{2}\', \'{3}\', \'{4}\', \'{5}\', \'{6}\'
		);';
	
	const SQL_UPDATE_SL_TRACKER		= 'UPDATE `{0}`
		SET  
		`TrackID` = \'{1}\',
		`UserID` = \'{2}\',
		`TrackType` = \'{3}\',
		`Value` = \'{4}\',
		`Description` = \'{5}\',	
		`TrackDate` = \'{6}\'
		
		WHERE `DistricID` = \'{1}\'  ';
		
	const SQL_CREATE_TABLE_SL_TRACKER		= '
                CREATE TABLE `{0}` (
                  `TrackID` bigint(20) NOT NULL,
                  `UserID` bigint(20) DEFAULT NULL,
                  `TrackType` varchar(50) DEFAULT NULL,
                  `Value` varchar(255) DEFAULT NULL,
                  `Description` varchar(255) DEFAULT NULL,
                  `TrackDate` datetime DEFAULT NULL,
                  PRIMARY KEY (`TrackID`)
                ) ENGINE=InnoDB DEFAULT CHARSET=latin1;';
	
	#endregion   
	
	#region Variables
	var $_objConnection;
	#end region
	
	#region Contructors
	/**
	*  Phuong th?c kh?i t?o d?i tu?ng faq d?ng th?i t?o connection d?n db
	*
	* @param object $objConnection ??i tu?ng k?t n?i d?n db
			
	* @return void 
	*
	*/
	public function  Model_Tracker($objConnection)
	{
		$this->_objConnection = $objConnection;
		
	}
	#region
	
	#region Public Functions
	
	public function insert( $userID,$trackType,$value,$description,$trackDate)
	{
		//$intID = global_common::getMaxID(self::TBL_SL_TRACKER);
		
		$strTableName = self::TBL_SL_TRACKER;
		$strSQL = global_common::prepareQuery(self::SQL_INSERT_SL_TRACKER,
				array(self::TBL_SL_TRACKER,$intID,global_common::escape_mysql_string($userID),
                global_common::escape_mysql_string($trackType),global_common::escape_mysql_string($value),
                global_common::escape_mysql_string($description),global_common::escape_mysql_string($trackDate)));
		
		if (!global_common::ExecutequeryWithCheckExistedTable($strSQL,self::SQL_CREATE_TABLE_SL_TRACKER,$this->_objConnection,$strTableName))
		{
			//echo $strSQL;
			global_common::writeLog('Error add SL_TRACKER:'.$strSQL,1);
			return false;
		}	
		return $intID;		
	}
	
	public function update($trackerID,$userID,$trackType,$value,$description,$trackDate)
	{
		$strTableName = self::TBL_SL_TRACKER;
		$strSQL = global_common::prepareQuery(self::SQL_UPDATE_SL_TRACKER,
				array($strTableName,global_common::escape_mysql_string($trackerID),
                global_common::escape_mysql_string($userID),global_common::escape_mysql_string($trackType),
                global_common::escape_mysql_string($value),global_common::escape_mysql_string($description),
                global_common::escape_mysql_string($trackDate)));
		
		if (!global_common::ExecutequeryWithCheckExistedTable($strSQL,self::SQL_CREATE_TABLE_SL_TRACKER,$this->_objConnection,$strTableName))
		{
			//echo $strSQL;
			global_common::writeLog('Error add SL_TRACKER:'.$strSQL,1);
			return false;
		}
		return $trackerID;
	}
	
	public function getTrackerByID($objID,$selectField='*') 
	{		
		$strSQL .= global_common::prepareQuery(global_common::SQL_SELECT_FREE, 
				array($selectField, self::TBL_SL_TRACKER ,							
					'WHERE TrackerID = \''.$objID.'\' '));
		//echo '<br>SQL:'.$strSQL;
		$arrResult =$this->_objConnection->selectCommand($strSQL);		
		if(!$arrResult)
		{
			global_common::writeLog('get SL_TRACKER ByID:'.$strSQL,1,$_mainFrame->pPage);
			return null;
		}
		//print_r($arrResult);
		return $arrResult[0];
	}	
    
	#endregion   
}
?>
