<?php
/*
 * This file was automatically generated By Code Smith 
 * Modifications will be overwritten when code smith is run
 *
 * PLEASE DO NOT MAKE MODIFICATIONS TO THIS FILE
 * Date Created 5/6/2012
 *
 */

/// <summary>
/// Implementations of slAdvertising represent a Advertising
///
/// </summary>
chdir("..");
/* TODO: Add code here */
require('config/globalconfig.php');
require('include/_permission_admin.inc');
include_once('class/model_user.php');
include_once('class/model_advertising.php');
include_once('class/model_adtype.php');
include_once('class/model_articletype.php');
include_once('class/model_article.php');
include_once('class/model_store.php');
include_once('class/model_storecategory.php');
require_once __DIR__.'/../lib/facebook/src/Facebook/autoload.php';
include_once('lib/facebook/src/Facebook/Facebook.php');
include_once('lib/facebook/src/Facebook/FacebookApp.php');
$objArticleType = new model_ArticleType($objConnection);
$objAdvertising = new Model_Advertising($objConnection);
$objAdType = new Model_AdType($objConnection);
$objArticle = new Model_Article($objConnection);
$objStore = new Model_Store($objConnection);
/*
$accessToken='CAABqohONX6ABAL6BQSXYZA5CwZAwXOd3H9QZBUPcPYF7XJBSoiFkQraA8EmOqaDKdRRff1FWilSS4DvYI73bwnW8AD6oeJoRC5eBTRBzvMlyLIrwRpbCBb36F3BDGgpsS6y0l1NHWyHRKJ6BdnZBAoFOrln5yYuS8RKDKEYKUTFTpVkmI0IMce9rvu5Quqay4MGxIOnKqAZDZD';
$fb = new Facebook\Facebook([
  'app_id' => '117244345278368',
  'app_secret' => '86eb5f2337c848fffdf44b150332489e',
  'default_graph_version' => 'v2.3',
  'default_access_token'=>$accessToken
  ]);
//print_r($fb);
$res = $fb->get('/me');
//print_r($res);;
echo '<br>';
 $posts= $fb->get("/7724542745_10153166070272746?fields=attachments");
//$posts = $fb->api("/7724542745/posts?limit=50");
print_r($posts);
return;
//$session = FacebookSession::newAppSession();    
//$access_token = $session->getAccessToken();
$session = new FacebookSession($accessToken);
*/


$catID = $_pgR["cid"];
$adTypeID = $_pgR["tid"];
$deleted = $_pgR["deleted"];
$condition='';
if($catID)
{
	$condition .= global_mapping::ArticleTypeID .'='.$catID.'';
}


if($deleted)
{
	$condition .= ' And '.global_mapping::IsDeleted.'=1';
}
else
{
	$condition .= ' And ('.global_mapping::IsDeleted.'=0 or '.global_mapping::IsDeleted.' is null)';
}
$allStores = $objStore->getStoresByCatID($catID,'`Name`,FacebookID');
//print_r($allStores);
//return;
//$allAds = $objAdvertising->getAllAdvertising(0,null,$condition,null);

$allAdType = $objAdType->getAllAdType(0,null,null,null);
$allCats = $objArticleType->getAllArticleType(0,null,'ParentID=0',null);


if($_pgR['act'] == 9999)
{
    //echo 'act 9999';
    $accessToken= $_facebookToken;
    $fb = new Facebook\Facebook([
                                'app_id' => $_facebookAppID,
                                'app_secret' => $_facebookSecrect,
                                'default_graph_version' => $_facebookVersion,
                                'default_access_token'=>$accessToken
                                ]);
    $posts = array();
    //print_r($allStores);
    //echo 'count($allStores) <br>';
    //echo count($allStores);
    //echo '<br>';
    $gotPosts = array();
    foreach ($allStores as $item)
    {
        //print_r($item);
        
        if(array_key_exists($item[global_mapping::FacebookID],$gotPosts) == false &&  $item[global_mapping::FacebookID])
        {
            //echo '<br>FacebookID:';
            //echo $item[global_mapping::FacebookID];
            $gotPosts[$item[global_mapping::FacebookID]] =$item[global_mapping::FacebookID];
            //print_r($res);;
            //echo '<br>Data<br>';
            //$response= $fb->get("/7724542745_10153166070272746?fields=description,attachments");
            //echo 'FacebookID:'.$item[global_mapping::FacebookID];
            $response= $fb->get('/'.$item[global_mapping::FacebookID].'?fields=id,name,posts');
            $newPosts = $response->getGraphObject() ->asArray() ;
            
            
            
            array_push ($posts,$newPosts);
            
            //print_r($newPosts);
            foreach($newPosts[global_mapping::fbposts] as $item)
            {
            	$postID = $item[global_mapping::fbid];
            	$pageID = $newPosts[global_mapping::fbid];
                //echo '<br>$postID:';
                //echo $postID;
                $existedArticle = $objArticle->getArticleByRefID($postID);
                //echo $existedArticle;
        	   	if ($existedArticle == false)
        		{
                    $response= $fb->get('/'.$postID.'?fields=message,description,attachments');   
                    $fbattachs = $response->getGraphObject() ->asArray() ;   
                    $content = $fbattachs[global_mapping::fbmessage];
                    $content = str_replace(array("\r\n", "\r", "\n"), '<br>', $content);        
                    foreach($fbattachs[global_mapping::fbattachments] as $item)
                    {
                        $content.= '<img src="'.$item[global_mapping::fbmedia][global_mapping::fbimage][global_mapping::fbsrc].'"/>';
                    } 
                    $c_userInfo = $_SESSION[global_common::SES_C_USERINFO]; 
                    $title =$fbattachs[global_mapping::fbdescription];
            		$title = html_entity_decode($title,ENT_COMPAT ,'UTF-8' );
            		//$content = $posts[global_mapping::fbmessage];
            		$content = html_entity_decode($content,ENT_COMPAT ,'UTF-8' );     		
            		
            		$renewedNum = 0;        		
            		$status = 1;
                    
            		$createdBy = $c_userInfo[global_mapping::UserID];
            		$arrCat = global_common::splitString($catalogueID);
                    
                    $stores = $objStore->getStoreByFBID($pageID);
                    $arrStoreID = global_common::getArrayColumn($stores,global_mapping::StoreID);
                    
            		$resultID = $objArticle->insert($title,$fileName, $content,null,$tags,$arrCat,$createdBy,
                        $renewedNum,$companyName,
    				    $companyAddress,$companyWebsite,$companyPhone,$adType,$startDate,$endDate,$happyDays,
    				    $startHappyHour,$endHappyHour, $addresses,$dictricts,$cities,$status,$arrStoreID,$postID);
                }
            }
            //break;
        }
    }   
    //print_r($posts);  
}

?>
<?php
$_SESSION[global_common::SES_C_CUR_PAGE] = "admin/admin_advertising.php";
include_once('include/_admin_header.inc');
?>
<script type="text/javascript" src="<?php echo $_objSystem->locateJs('user_article.js');?>"></script>
<div id="admin-advertising">
	<div class="row-fluid">
		<div class="span12">
			<!-- BEGIN PAGE TITLE & BREADCRUMB-->
			<h3 class="page-title">
				Crawl data from facebook
			</h3>
		</div>
	</div>
	
	 <div class="row-fluid">	
            <div class="span12">
				<input type="hidden" id="adddocmode" name="adddocmode" value="" />
				<input type="hidden" id="AdvertisingID" name="AdvertisingID" value="" />
			<!--a href='javascript:advertising.showPopupAdd("modal-add")' class="btn" title="Add new advertising"><i class="icon-plus"></i> Add New</a-->
	<div class="portlet box">
		<div class="portlet-title hide">
			<div class="caption">
				<!--i class="icon-reorder"></i-->
			</div>
			
			<div class="tools">                                
				<!--a href="#config-form" data-toggle="modal" class="config"></a-->
				<!--a href="javascript:;" class="reload" title="Reload"></a-->
			</div>
			<div class="actions">									
				
			</div>
		</div>
		<!---->
		<div class="portlet-body">
		<form method="get" id="form-article" style="display: inline-flex">
<select class="" name="cid" id="cid" style="height:25px">
<option value="0" >ALL</option>
<?php
foreach($allCats as $item)
{
	$isSelect = false;
	//print_r($currentTypes);
	
	if($item[global_mapping::ArticleTypeID] == $catID)
	{
		$isSelect=true;
	}
	if($isSelect)
		echo '			<option selected="selected" value="'.$item[global_mapping::ArticleTypeID].'" >'.$item[global_mapping::ArticleTypeName].'</option>';
	else
		echo '			<option value="'.$item[global_mapping::ArticleTypeID].'" >'.$item[global_mapping::ArticleTypeName].'</option>';
}
?>		
</select>	
<select class="" name="tid" id="cid" style="height:25px;display:none">
	<option value="0" >ALL</option>
<?php
foreach($allAdType as $item)
{
	$isSelect = false;
	//print_r($currentTypes);
	
	if($item[global_mapping::AdTypeID] == $adTypeID)
	{
		$isSelect=true;
	}
	if($isSelect)
		echo '			<option selected="selected" value="'.$item[global_mapping::AdTypeID].'" >'.$item[global_mapping::AdTypeName].'</option>';
	else
		echo '			<option value="'.$item[global_mapping::AdTypeID].'" >'.$item[global_mapping::AdTypeName].'</option>';
}
?>	
</select>	
<label for="deleted" style="height:20px;color:black; margin: 0 0 0 10px">Deleted: </label> <input type="checkbox" <?php echo ($deleted?'checked=checked':'') ?> name="deleted" id="deleted" value="true" />
<input type="hidden" value="9999" id="act" name="act" />
<input type="submit" value="Search" style="height:24px;margin:0 10px" />		
</form>		
									
<?php
//print_r($advertising);
if($posts)
{
	echo '<table class="table table-striped">';
	echo '<thead>';
	echo '<th>';
	echo 'StoreName';		
	echo '</th>';
	echo '<th>';
	echo 'Post';		
	echo '</th>';
	echo '<th>';
	echo 'Post date';		
	echo '</th>';    
	echo '<th>';
	echo 'Action';		
	echo '</th>';
	echo '</thead>';
   foreach($posts as $post)
   {
    	foreach($post[global_mapping::fbposts] as $item)
    	{
    		echo '<tr>';
    		echo '<td>';
    		echo $post[global_mapping::fbname];		
    		echo '</td>';	
    		echo '<td style="">';
    		echo $item[global_mapping::fbmessage];		
    		echo '</td>';	
    		echo '<td>';
           // $datefb= date_create($item[global_mapping::fbcreated_time]);
            echo date_format($item[global_mapping::fbcreated_time],'Y/m/d H:i:s');
    	//	echo global_common::formatDateVN($item[global_mapping::fbcreated_time]);		
    		echo '</td>';	
    		echo '<td style="padding:0;width:180px">';
    		echo '<a href="javascript:article.approveFbArticle(\''.$item[global_mapping::fbid].'\',\''.$post[global_mapping::fbid].'\')" class="btn btn-mini">Approve</a> ';	
    		echo '</td>';
    		echo '</tr>';
    	}
    }
	echo '</table>';
}
?>
				</div>
					</div>
		</div>
	</div>
</div>
<?php
include_once('include/_admin_footer.inc');
?>


<div id="modal-add" class="modal hide fade" tabindex="-1" data-width="800" data-keyboard="false"  aria-hidden="true" data-backdrop="static">
    <div class="modal-header">
        <!--button type="button" class="close" data-dismiss="modal" aria-hidden="true">
        </button-->
        <h3 class="popup-title">Add new advertising
        </h3>
    </div>
    <div class="modal-body">
		
		 <!-- BEGIN FORM-->
        <form class="form-horizontal" action="#">
		<div class="control-group">
			<div class="controls">
				<!--label class="m-wrap">(*) là thông tin b?t bu?c</label-->
			</div>
		</div>
        <div class="control-group">
            <label class="control-label">
                Name</label>
            <div class="controls">
                <input type="text" id="txtAdName" class="span5">
            </div>
        </div>
		 <div class="control-group">
            <label class="control-label">
                Advertising Type 
            </label>
            <div class="controls">
                <select tabindex="1" class="span5" id="cmAdType">
<?php
foreach($allAdType as $item)
{
	echo '			<option value="'.$item[global_mapping::AdTypeID].'" >'.$item[global_mapping::AdTypeName].'</option>';
	
}
?>
                </select>
            </div>
        </div>	
		<div class="control-group">
            <label class="control-label">
                Category Type 
            </label>
            <div class="controls">
                <select tabindex="1" class="span5" id="cmCatType">
<?php
foreach($allCats as $item)
{
	echo '			<option value="'.$item[global_mapping::ArticleTypeID].'" >'.$item[global_mapping::ArticleTypeName].'</option>';
	
}
?>
                </select>
            </div>
        </div>	
		<div class="control-group">
            <label class="control-label">
                Order </label>
            <div class="controls">
                <input type="text" id="txtOrder" class="span5">
            </div>
        </div>		
        <div class="control-group">
            <label class="control-label">
                Start Date </label>
            <div class="controls">
                	<div class="input-append date date-picker text " data-date="" readonly="readonly"  data-date-format="dd/mm/yyyy"  data-date-viewmode="days">
					<input name="txtStartDate" id="txtStartDate" disabled="disabled" class="m-wrap m-ctrl-medium date-picker"
					size="16" type="text" placeholder="dd/mm/yyyy" value=""/>
						<span class="add-on"><i class="icon-calendar"></i></span>
				</div>
            </div>
        </div>
		<div class="control-group">
            <label class="control-label">
                End Date </label>
            <div class="controls">
               	<div class="input-append date date-picker text " data-date="" readonly="readonly"  data-date-format="dd/mm/yyyy"  data-date-viewmode="days">
					<input name="txtEndDate" id="txtEndDate" disabled="disabled" class="m-wrap m-ctrl-medium date-picker"
					size="16" type="text" placeholder="dd/mm/yyyy" value=""/>
						<span class="add-on"><i class="icon-calendar"></i></span>
				</div>
            </div>
        </div>
		<div class="control-group">
            <label class="control-label">
                Image Link 
            </label>
            <div class="controls">
                 <input id="txtImageLink" type="text" class="span5">
            </div>
        </div>
		<div class="control-group">
            <label class="control-label">
                Prefer Link 
            </label>
            <div class="controls">
                 <input id="txtPreferLink" type="text" class="span5">
            </div>
        </div>
		<div class="control-group">
            <label class="control-label">
                Content </label>
            <div class="controls">
                <textarea  id="txtContent" class="span5" rows="3"></textarea>
            </div>
        </div>
        <div class="control-group">
            <label class="control-label">
                Partner Info </label>
            <div class="controls">
                <textarea  id="txtPartner" class="span5" rows="3"></textarea>
            </div>
        </div>
       
        </form>
        <!-- END FORM-->
	</div>
	 <div class="modal-footer">
		<div class="pull-right">
			<a href="javascript:advertising.addAdverting();" class="btn" id="btnSave">Save</a>
			<a href="javascript:;" class="btn btn-mini" data-dismiss="modal"   aria-hidden="true">Cancel</a>        
		</div>
		 <div class="controls pull-right">
			<label class="checkbox ckCreateOther">
				<div class="checker">
					<span class="">
						<input type="checkbox" value=""></span>
				</div>
				Create another
			</label>
		</div>
	</div>
</div>